language: node_js
node_js:
- '10'
after_success:
- git config --global user.name "verge-travis"
- git config --global user.email "verge-travis@users.noreply.github.com"
- git remote rm origin
- git remote add origin git@github.com:vergecurrency/vergecurrency.com.git
- yarn run deploy
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv  || true
  -in deploy_key.enc -out /tmp/deploy_key -d  || true
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key  || true
- ssh-add /tmp/deploy_key  || true
